### ISSUE TITLE
Return type of Parse()

### ISSUE THREAD

**Issue by r-tae** [leodido/go-conventionalcommits#20]
I'm relatively new to Go so I'm not sure if I'm missing something here, but going by the documentation (and therefore gopls) Parse returns Message. This means gopls has no idea that any of the parsed fields exist, is this a bug or is this somehow required to provide optional fields?

**Comment by verysonglaa** [comment]
Do it with type conversion:

```
p := parser.NewMachine(conventionalcommits.WithBestEffort())
commit := []byte("feat: feature")
i, err := p.Parse(commit)
CheckIfError(err)
res, ok := i.(*conventionalcommits.ConventionalCommit)
if !ok {
fmt.Println("Parse failed")
}
fmt.Println(res.Description)
```

**Comment by leodido** [comment]
Thank you @verysonglaa for assisting!

Closing
