### ISSUE TITLE
Retrieving the type?

### ISSUE THREAD

**Issue by patrickjane** [leodido/go-conventionalcommits#35]
Is there a way to retrieve the parsed type after parsing, in addition to the bools which can be queried?

**Comment by leodido** [comment]
Do you mean this field in the `ConvetionalCommit` struct? :)

https://github.com/leodido/go-conventionalcommits/blob/2713df998a1596207af6090215be9cbe2fd651be/conventional_commit.go#L75

**Comment by patrickjane** [comment]
Well the `Parse()` method returns a `Message`-object, which does not have a type field?
Tbh, the API is not very intuitive, and the examples on the github frontpage could be a bit more detailed.

How do I retrieve the type then?

**Comment by leodido** [comment]
The `Parse()` returns an interface you can cast to a pointer of the specific type. It's not about this API, it's a common pattern in Go...

Something like the following line should work:

```go
cc, _ := msg.(*conventionalcommits.ConventionalCommit)
fmt.Println(cc.Type)
```

**Comment by patrickjane** [comment]
Surely, but how would I know without inspecting the code?

Thanks anyway!
